import {
  Bot,
  Brain,
  Cable,
  CreditCard,
  FileText,
  Gauge,
  Home,
  Key,
  Link2,
  Settings,
  Shield,
  User,
  Wallet,
  Wrench,
  Zap,
} from "lucide-react";

export const navItems = [
  { href: "/", label: "Home", icon: Home },
  { href: "/workflows", label: "Workflows", icon: Zap },
  { href: "/agents", label: "Agents", icon: Bot },
  { href: "/wallets", label: "Wallets", icon: Wallet },
  { href: "/mcps", label: "MCPs", icon: Cable },
  { href: "/rag", label: "RAG", icon: FileText },
  { href: "/skills", label: "Skills", icon: Brain },
  { href: "/apis", label: "My APIs", icon: Key },
  { href: "/treasury", label: "Treasury", icon: CreditCard },
  { href: "/limits", label: "Limits", icon: Gauge },
  { href: "/integrations", label: "Integrations", icon: Link2 },
  { href: "/harness", label: "Harness", icon: Wrench },
  { href: "/account", label: "Account", icon: User },
  { href: "/profile", label: "Profile", icon: Shield },
  { href: "/settings", label: "Settings", icon: Settings },
] as const;
