// Source language. Marketing copy for people who put money behind agents; the Portuguese file
// mirrors every key. No prices, no "non-custodial", no audit promises (tests enforce the first two).
// Every number here is checked against the agent-rails repo before it changes; see the
// writing-ash-marketing-copy skill for the tone contract and the gain-first framing.
export const en = {
  meta: {
    title: "Ash — turn prompts into payments on Solana",
    description:
      "Turn prompts into payments. Ash gives AI agents on Solana full autonomy on your terms: a budget and a list of destinations you set once, enforced by an on-chain program, with an on-chain record of every payment.",
  },
  nav: {
    how: "How it works", proof: "Record", who: "Who it’s for", cta: "Book 20 minutes", lang: "PT",
    sections: "Sections", skip: "Skip to content",
  },
  hero: {
    eyebrow: "Spend authority for AI agents · on Solana",
    title: "Unleash your agents on Solana. Full autonomy, on your terms.",
    sub: "Turn prompts into payments. Your agent pays for APIs, compute and vendors on its own — no key to your whole balance in an env file, no human approving each payment. You set a budget and a list of destinations once; a program on Solana refuses anything outside them, and you withdraw alone, any time.",
    cta1: "Book 20 minutes",
    cta2: "See the program on devnet",
    status: "Devnet only, unaudited, and the program can still be upgraded by a single key of ours. Mainnet waits for a professional audit.",
    unit: "Ash · unit 01", online: "online",
    mascotAlt: "Ash, the robot mascot, giving a thumbs up",
    scene: { balance: "treasury", ceiling: "per-payment limit", hint: "drag the limit", settled: "settled", refused: "refused", unknown: "unknown" },
  },
  momentum: {
    eyebrow: "Why now",
    title: "The rails are live. Almost no agent rides them yet.",
    stat: "TRM Labs counted 52.7 million dollars in x402 settlements since May 2025. About 25.6 million look like commerce after its filters, and only 0.6% to 7.5% of that looks like AI agents.",
    note: "Before an agent holds a real balance, someone has to bound what it can do with it. Ash is that bound: who sets it, where the money may go, and the record that it held. It does not connect to x402 yet.",
  },
  showcase: {
    eyebrow: "See it run",
    title: "Every agent gets its own budget.",
    sub: "One paid a vendor. One tried to spend past its limit and the program refused it on the spot. One had its session revoked and cannot move a cent. Simulated data; the rules are the ones the program enforces on devnet.",
    demo: "simulated", run: "run a payment",
    kpi: { spent: "Spent today", active: "Agents active", denied: "Denied today" },
    vault: "Vault", ceiling: "Ceiling", guardian: "Guardian", perDay: "/day", left: "left today", balance: "bal",
    noSpend: "No spend permission · routes work", today: "today",
    status: { active: "active", paused: "revoked", routes: "routes" },
    agents: {
      ana: { n: "Ana", r: "Support" }, joao: { n: "João", r: "Sales assistant" },
      maria: { n: "Maria", r: "Finance" }, carlos: { n: "Carlos", r: "Logistics" },
    },
    payees: { customers: "Customers", marketing: "Marketing", openai: "OpenAI", vendors: "Vendors", carriers: "Carriers" },
    handoffs: { lead: "lead", refund: "refund", shipment: "shipment" },
    legend: { funding: "Funding", payment: "Payment", handoff: "Handoff", paused: "Revoked", ceiling: "Ceiling" },
    feed: {
      title: "Activity", where: "simulated · same rules as devnet",
      settled: "settled", denied: "denied", blocked: "blocked", handoff: "handoff",
      overLimit: "over the limit", paused: "session revoked by the operator",
    },
  },
  pain: {
    title: "Handing an agent a wallet is signing a blank cheque.",
    items: [
      { t: "A web page tells it to withdraw everything.", b: "If a withdraw tool exists, one sentence in the input can get it called." },
      { t: "The call times out. The agent retries.", b: "The first transfer had already landed. Now it lands twice." },
      { t: "The key in the env file leaks.", b: "A limit held off-chain belongs to whoever holds the process." },
    ],
    closer: "In all three, the whole balance is exposed. A small wallet topped up by hand caps the damage — for one agent and a few cents. It does not stretch to four agents and a real vendor.",
  },
  pay: {
    title: "Agents that pay.",
    sub: "The agent pays for APIs, vendors and fees on its own. No one approves each payment, and no one has to.",
    items: [
      { t: "It pays without asking.", b: "A session key signs each payment within policy. You set the rules once; the agent works until the session expires." },
      { t: "It can’t raise its own limit.", b: "The agent sees seven tools. Six read or pay; the seventh only asks a human. None withdraws, raises a limit or lifts a pause." },
      { t: "A retry does not pay twice.", b: "The on-chain receipt refuses the duplicate while it exists — at least an hour. If the network goes quiet, the agent waits instead of guessing." },
      { t: "It plugs into what you run.", b: "MCP for Claude Desktop and Cursor, a Vercel AI SDK adapter, SOL, SPL and Token-2022 tokens (no transfer hooks, no confidential transfers)." },
    ],
  },
  roles: {
    title: "Rules that hold.",
    sub: "Think of a corporate card shared by four people. No policy exceeds the owner’s ceiling, and no agent changes its own policy.",
    items: [
      { n: "Owner", b: "Funds the treasury, sets the ceiling, can switch everything off. Withdraws alone, even while the vault is paused." },
      { n: "Operator", b: "Runs the day-to-day policy under the ceiling: who gets paid and how many agents exist. Cannot raise the ceiling or call withdraw — and its key deserves the same care as the owner’s." },
      { n: "Guardian", b: "Holds one button: pause. The worst a rogue guardian can do is stop every agent in the vault." },
      { n: "Agent", b: "Pays within policy until its session expires. Its key authorizes payments, never limits." },
    ],
    limits: "Per-payment, per-window and lifetime limits apply at once, per agent session and per token, with a list of allowed destinations and up to four tokens. Tightening any of them counts from the next payment.",
    rule: "The rules live in a program on the network. Not on our servers, and not in the agent’s prompt.",
  },
  proof: {
    title: "A record on-chain.",
    sub: "Each payment extends a hash chain whose head lives on-chain. With the full history in hand, anyone can confirm nothing was left out; keeping that history long-term still depends on an indexer we have not built.",
    stats: [
      { v: 13, s: "", l: "Kani proofs over the policy core" },
      { v: 99.2, s: "%", l: "line coverage on the policy engine" },
    ],
    link: "See the program on Solana Explorer",
    process: "More than twenty architecture decisions on record, each written next to the alternatives it rejected.",
  },
  who: {
    title: "Who it’s for",
    doors: [
      { t: "You build agents", b: "Your agent should pay for compute, APIs and data on its own. Today that means a funded key in an env file, or a human clicking approve. Plug in the MCP server or the Vercel AI SDK adapter and it pays inside a budget you did not have to code.", cta: "Book 20 minutes" },
      { t: "Your team or DAO pays out by hand", b: "Bounties, refunds, micro-grants: give a bot petty cash with a ceiling. Small payments go out on their own; anything outside the budget is refused, and the agent can ask a human for more.", cta: "Book 20 minutes" },
      { t: "You run agents in DeFi", b: "A mandate an agent cannot leave — this venue, this much a day — is what lets capital sit behind a model. Not built yet: today the program pays destinations, it does not trade. We want the first desks to shape it.", cta: "Talk to us" },
    ],
    note: "Apache-2.0 licensed. No protocol fee today.",
  },
  objection: {
    title: "Why not Solana’s native allowances?",
    sub: "We use them. The native cap is free and audited — and it is one number. Hand that delegation to the agent’s own wallet and the agent can go around any policy placed in front of it. In Ash, the vault holds it.",
    head: ["Native allowances alone", "Ash"],
    rows: [
      ["One delegate, one cap", "Per-payment, per-window and lifetime limits at once"],
      ["Delegated to the agent’s wallet, the agent can pull directly", "The vault is the delegate; the agent’s key cannot pull directly"],
      ["The owner is the only brake", "A pause key separate from the owner"],
      ["History as good as your indexer", "A hash chain that lets you prove nothing was deleted"],
    ],
    note: "Ash composes with the native primitive. We build on it, not against it.",
  },
  closing: {
    title: "Ready to let an agent pay?",
    sub: "Twenty minutes: what your agent should pay for, what stops you from letting it, what you have tried. We are looking for our first teams and will tell you plainly whether Ash fits.",
    cta: "Book 20 minutes",
    alt: "or write to",
    bubble: "budget approved", mascotAlt: "Ash, the robot mascot, up close",
  },
  footer: { line: "Ash · Apache-2.0 · devnet only, unaudited", privacy: "Privacy" },
  notFound: { title: "This page does not exist.", body: "The address may be mistyped, or the page may have moved.", home: "Back to the home page" },
  privacy: {
    title: "Privacy",
    body: [
      "Data controller and data protection officer (Brazil's LGPD): Lucas Lopes Galvão, as an individual, until Ash's company is incorporated — when it is, this page changes and we tell everyone on the list. Contact: lgpd@ash.app.br.",
      "This site sets no cookies and runs no analytics scripts. Fonts are served from this domain.",
      "If you book a call or write to us, we keep your name, e-mail and what you tell us only to hold that conversation. Ask and we delete it.",
      "The investor page asks, with your consent, for your name, role, what you do (investor, founder or something else) and e-mail, so we can talk to you about Ash. The same pitch is open to anyone without the form.",
      "We keep those details in a Cloudflare D1 database and in our e-mail tool (Listmonk) on our own server, both in the United States. We do not store your IP address. Your browser keeps only your name, that choice and a random reference number, to greet you next time. If at the end you say you want to talk, we note when and through which channel.",
      "We e-mail you only after you confirm your address, and every e-mail has an unsubscribe link. We keep the details until you ask us to remove them, or for 24 months without contact. Only the Ash team can see them. The legal basis is your consent, which you can withdraw at any time. To confirm processing, or to see, correct, export or delete your details, write to lgpd@ash.app.br or reply to any e-mail we send; you can also complain to Brazil's data protection authority (ANPD).",
      "The form uses Cloudflare Turnstile to keep bots out; Cloudflare processes technical signals from your browser for that check.",
      "Hosting: Cloudflare Pages. Cloudflare sees the request logs any web host sees.",
    ],
    back: "Back to the site",
  },
  // Interface labels of the blog. The posts themselves come from the studio. The two cards reuse
  // sentences that already stand above (hero, closing): a post must not promise something new.
  blog: {
    nav: "Blog",
    title: "Blog",
    intro: "Notes from the people building Ash, on how agents pay and the rules around it.",
    // Meta descriptions of the list pages. {name}, {page} and {total} are filled by the page.
    desc: {
      category: "Posts in {name} on the Ash blog.",
      tag: "Posts tagged {name} on the Ash blog.",
      author: "Posts by {name} on the Ash blog.",
      page: "Page {page} of {total} of the Ash blog.",
    },
    search: {
      label: "Search the blog",
      placeholder: "Search posts",
      hint: "Type a word to search the posts.",
      none: "No post matches {query}.",
      count: { one: "1 result", other: "{count} results" },
      loading: "Searching…",
      failed: "Search is not available right now.",
      results: "Results",
    },
    readMore: "Read more",
    published: "Published",
    updated: "Updated",
    minRead: "min read",
    by: "By",
    featured: "Featured",
    related: "Related posts",
    tags: "Tags",
    tag: "Tag",
    category: "Category",
    categories: "Categories",
    author: "Author",
    allPosts: "All posts",
    newer: "Newer",
    older: "Older",
    page: "Page",
    of: "of",
    pagination: "Pagination",
    share: "Share",
    copyLink: "Copy link",
    copied: "Copied",
    email: "E-mail",
    toc: "On this page",
    rss: "RSS feed",
    // The link to the other language's version, written in that language.
    translation: "Leia em português",
    empty: "Nothing published here yet.",
    cta: {
      pitch: {
        title: "Unleash your agents on Solana. Full autonomy, on your terms.",
        body: "Spend authority for AI agents on Solana. Devnet only, unaudited.",
        button: "See the pitch",
      },
      contact: {
        title: "Ready to let an agent pay?",
        body: "Twenty minutes: what your agent should pay for, what stops you from letting it, what you have tried.",
        channels: { booking: "Book 20 minutes", whatsapp: "WhatsApp", email: "E-mail" },
        whatsappText: "Hi, I read the Ash blog and would like to talk.",
        emailSubject: "Ash — from the blog",
      },
    },
  },
} as const;
