// Tradução de copy.en.ts, chave por chave. O teste de paridade falha se uma faltar.
export const pt = {
  meta: {
    title: "Ash — transforme prompts em pagamentos na Solana",
    description:
      "Transforme prompts em pagamentos. O Ash dá a agentes de IA na Solana autonomia total nos seus termos: um orçamento e uma lista de destinos que você define uma vez, impostos por um programa on-chain, com registro on-chain de cada pagamento.",
  },
  nav: {
    how: "Como funciona", proof: "Registro", who: "Para quem", cta: "Agendar 20 minutos", lang: "EN",
    sections: "Seções", skip: "Pular para o conteúdo",
  },
  hero: {
    eyebrow: "Autoridade de gasto para agentes de IA · na Solana",
    title: "Solte seus agentes na Solana. Autonomia total, nos seus termos.",
    sub: "Transforme prompts em pagamentos. Seu agente paga APIs, computação e fornecedores sozinho — sem a chave do saldo inteiro num arquivo .env, sem ninguém aprovando cada pagamento. Você define um orçamento e uma lista de destinos uma vez; um programa na Solana recusa o que sair disso, e você saca sozinho, a qualquer hora.",
    cta1: "Agendar 20 minutos",
    cta2: "Ver o programa na devnet",
    status: "Só devnet, sem auditoria, e o programa ainda pode ser atualizado por uma única chave nossa. A mainnet espera uma auditoria profissional.",
    unit: "Ash · unidade 01", online: "online",
    mascotAlt: "Ash, o robô mascote, fazendo sinal de positivo",
    scene: { balance: "cofre", ceiling: "limite por pagamento", hint: "arraste o limite", settled: "liquidado", refused: "recusado", unknown: "desconhecido" },
  },
  momentum: {
    eyebrow: "Por que agora",
    title: "Os trilhos estão no ar. Quase nenhum agente anda neles ainda.",
    stat: "A TRM Labs contou 52,7 milhões de dólares em liquidações x402 desde maio de 2025. Cerca de 25,6 milhões parecem comércio depois dos filtros dela, e só 0,6% a 7,5% disso parece agente de IA.",
    note: "Antes de um agente guardar um saldo de verdade, alguém precisa delimitar o que ele faz com esse saldo. O Ash é esse limite: quem define, para onde o dinheiro vai, e o registro de que foi respeitado. Ainda não se conecta ao x402.",
  },
  showcase: {
    eyebrow: "Veja funcionando",
    title: "Cada agente com o seu próprio orçamento.",
    sub: "Um pagou um fornecedor. Outro tentou gastar além do limite e o programa recusou na hora. Outro teve a sessão revogada e não move um centavo. Dados simulados; as regras são as mesmas que o programa impõe na devnet.",
    demo: "simulação", run: "simular um pagamento",
    kpi: { spent: "Gasto hoje", active: "Agentes ativos", denied: "Negados hoje" },
    vault: "Cofre", ceiling: "Teto", guardian: "Guardião", perDay: "/dia", left: "restam hoje", balance: "saldo",
    noSpend: "Sem permissão de gasto · repassa trabalho", today: "hoje",
    status: { active: "ativo", paused: "revogado", routes: "repassa" },
    agents: {
      ana: { n: "Ana", r: "Suporte" }, joao: { n: "João", r: "Vendas" },
      maria: { n: "Maria", r: "Financeiro" }, carlos: { n: "Carlos", r: "Logística" },
    },
    payees: { customers: "Clientes", marketing: "Marketing", openai: "OpenAI", vendors: "Fornecedores", carriers: "Transportadoras" },
    handoffs: { lead: "lead", refund: "reembolso", shipment: "envio" },
    legend: { funding: "Abastece", payment: "Pagamento", handoff: "Repasse", paused: "Revogado", ceiling: "Teto" },
    feed: {
      title: "Atividade", where: "simulação · mesmas regras da devnet",
      settled: "liquidado", denied: "negado", blocked: "bloqueado", handoff: "repasse",
      overLimit: "acima do limite", paused: "sessão revogada pelo operador",
    },
  },
  pain: {
    title: "Entregar uma carteira a um agente é assinar um cheque em branco.",
    items: [
      { t: "Uma página manda sacar tudo.", b: "Se existe uma ferramenta de saque, uma frase na entrada basta para ela ser chamada." },
      { t: "A chamada estoura o tempo. O agente tenta de novo.", b: "A primeira transferência já tinha entrado. Agora entra duas vezes." },
      { t: "A chave no arquivo .env vaza.", b: "Limite guardado fora da rede pertence a quem controla o processo." },
    ],
    closer: "Nos três casos, o saldo inteiro fica exposto. Uma carteira pequena reabastecida à mão limita o estrago — para um agente e alguns centavos. Não dá conta de quatro agentes e um fornecedor de verdade.",
  },
  pay: {
    title: "Agentes que pagam.",
    sub: "O agente paga APIs, fornecedores e taxas sozinho. Ninguém aprova cada pagamento, e ninguém precisa.",
    items: [
      { t: "Ele paga sem pedir licença.", b: "Uma chave de sessão assina cada pagamento dentro da política. Você define as regras uma vez; o agente trabalha até a sessão vencer." },
      { t: "Ele não sobe o próprio limite.", b: "O agente enxerga sete ferramentas. Seis leem ou pagam; a sétima só pede a um humano. Nenhuma saca, sobe limite ou tira a pausa." },
      { t: "Tentar de novo não paga duas vezes.", b: "O recibo on-chain recusa a duplicata enquanto existir — pelo menos uma hora. Se a rede fica em silêncio, o agente espera em vez de chutar." },
      { t: "Ele se liga no que você já usa.", b: "MCP para Claude Desktop e Cursor, adaptador para o Vercel AI SDK, SOL, tokens SPL e Token-2022 (sem transfer hooks nem transferências confidenciais)." },
    ],
  },
  roles: {
    title: "Regras que se sustentam.",
    sub: "Pense num cartão corporativo dividido por quatro pessoas. Nenhuma política passa do teto do dono, e nenhum agente muda a própria política.",
    items: [
      { n: "Dono", b: "Abastece o cofre, define o teto, pode desligar tudo. Saca sozinho, mesmo com o cofre pausado." },
      { n: "Operador", b: "Cuida da política do dia a dia abaixo do teto: quem recebe e quantos agentes existem. Não sobe o teto nem saca — e a chave dele merece o mesmo cuidado que a do dono." },
      { n: "Guardião", b: "Tem um botão só: pausar. O pior que um guardião traidor faz é parar todos os agentes do cofre." },
      { n: "Agente", b: "Paga dentro da política até a sessão vencer. A chave dele autoriza pagamentos, nunca limites." },
    ],
    limits: "Limites por pagamento, por janela e no total valem ao mesmo tempo, por sessão de agente e por token, com uma lista de destinos permitidos e até quatro tokens. Apertar qualquer um vale a partir do pagamento seguinte.",
    rule: "As regras moram num programa na rede. Não nos nossos servidores, e não no prompt do agente.",
  },
  proof: {
    title: "Um registro on-chain.",
    sub: "Cada pagamento estende uma cadeia de hash cuja ponta fica on-chain. Com o histórico completo em mãos, qualquer um confirma que nada ficou de fora; guardar esse histórico no longo prazo ainda depende de um indexer que não construímos.",
    stats: [
      { v: 13, s: "", l: "provas Kani sobre o núcleo de política" },
      { v: 99.2, s: "%", l: "de cobertura de linhas no motor de política" },
    ],
    link: "Ver o programa no Solana Explorer",
    process: "Mais de vinte decisões de arquitetura registradas, cada uma escrita ao lado das alternativas que descartou.",
  },
  who: {
    title: "Para quem",
    doors: [
      { t: "Você constrói agentes", b: "Seu agente deveria pagar computação, APIs e dados sozinho. Hoje isso é uma chave com saldo num arquivo .env, ou um humano clicando em aprovar. Ligue o servidor MCP ou o adaptador do Vercel AI SDK e ele paga dentro de um orçamento que você não precisou programar.", cta: "Agendar 20 minutos" },
      { t: "Seu time ou DAO paga na mão", b: "Bounties, reembolsos, microgrants: dê a um bot um caixa pequeno com teto. Os pagamentos pequenos saem sozinhos; o que passa do orçamento é recusado, e o agente pode pedir mais a um humano.", cta: "Agendar 20 minutos" },
      { t: "Você roda agentes em DeFi", b: "Um mandato do qual o agente não sai — este local, este tanto por dia — é o que deixa capital ficar atrás de um modelo. Ainda não construído: hoje o programa paga destinos, não opera ativos. Queremos que as primeiras mesas deem forma a ele.", cta: "Falar com a gente" },
    ],
    note: "Licença Apache-2.0. Hoje não há taxa de protocolo.",
  },
  objection: {
    title: "Por que não o Allowances nativo da Solana?",
    sub: "A gente usa. O teto nativo é grátis e auditado — e é um número só. Entregue essa delegação à carteira do próprio agente e ele contorna qualquer política colocada na frente. No Ash, quem a segura é o cofre.",
    head: ["Só o Allowances nativo", "Ash"],
    rows: [
      ["Um delegado, um teto", "Limites por pagamento, por janela e no total, ao mesmo tempo"],
      ["Delegado à carteira do agente, o agente puxa direto", "O cofre é o delegado; a chave do agente não puxa direto"],
      ["O dono é o único freio", "Uma chave de pausa separada do dono"],
      ["Histórico tão bom quanto o seu indexer", "Uma cadeia de hash que permite provar que nada foi apagado"],
    ],
    note: "O Ash se compõe com a primitiva nativa. Construímos em cima dela, não contra.",
  },
  closing: {
    title: "Pronto para deixar um agente pagar?",
    sub: "Vinte minutos: o que o seu agente deveria pagar, o que impede você de deixar, o que já tentou. Estamos procurando os primeiros times e diremos com franqueza se o Ash serve para você.",
    cta: "Agendar 20 minutos",
    alt: "ou escreva para",
    bubble: "orçamento aprovado", mascotAlt: "Ash, o robô mascote, de perto",
  },
  footer: { line: "Ash · Apache-2.0 · só devnet, sem auditoria", privacy: "Privacidade" },
  notFound: { title: "Esta página não existe.", body: "O endereço pode ter sido digitado errado, ou a página mudou de lugar.", home: "Voltar para a página inicial" },
  privacy: {
    title: "Privacidade",
    body: [
      "Controlador e encarregado pelo tratamento de dados (LGPD): Lucas Lopes Galvão, pessoa física, até a constituição da empresa do Ash — quando ela existir, esta página muda e avisamos quem estiver na lista. Contato: lgpd@ash.app.br.",
      "Este site não usa cookies nem scripts de analytics. As fontes são servidas deste domínio.",
      "Se você agendar uma conversa ou escrever, guardamos nome, e-mail e o que você contou só para essa conversa. Pediu, apagamos.",
      "A página para investidores pede, com o seu consentimento, nome, cargo, o que você faz (investidor, empreendedor ou outra coisa) e e-mail, para conversarmos sobre o Ash. O mesmo pitch está aberto para qualquer pessoa, sem o formulário.",
      "Guardamos esses dados num banco Cloudflare D1 e na nossa ferramenta de e-mail (Listmonk), no nosso próprio servidor, ambos nos Estados Unidos. Não guardamos o seu endereço IP. O seu navegador guarda só o seu nome, aquela escolha e um número de referência aleatório, para te cumprimentar na próxima visita. Se no final você disser que quer conversar, anotamos quando e por qual canal.",
      "Só escrevemos depois que você confirma o endereço, e todo e-mail tem link para sair. Guardamos os dados até você pedir para remover, ou por 24 meses sem contato. Só o time do Ash tem acesso. A base legal é o seu consentimento, que você pode retirar quando quiser. Para confirmar o tratamento, ver, corrigir, levar ou apagar os seus dados, escreva para lgpd@ash.app.br ou responda a qualquer e-mail nosso; você também pode reclamar à ANPD.",
      "O formulário usa o Cloudflare Turnstile para barrar robôs; a Cloudflare processa sinais técnicos do seu navegador nessa checagem.",
      "Hospedagem: Cloudflare Pages. A Cloudflare vê os logs de requisição que qualquer hospedagem vê.",
    ],
    back: "Voltar ao site",
  },
  blog: {
    nav: "Blog",
    title: "Blog",
    intro: "Notas de quem constrói o Ash, sobre como agentes pagam e as regras em volta disso.",
    desc: {
      category: "Posts em {name} no blog do Ash.",
      tag: "Posts com a tag {name} no blog do Ash.",
      author: "Posts de {name} no blog do Ash.",
      page: "Página {page} de {total} do blog do Ash.",
    },
    search: {
      label: "Buscar no blog",
      placeholder: "Buscar posts",
      hint: "Digite uma palavra para buscar nos posts.",
      none: "Nenhum post corresponde a {query}.",
      count: { one: "1 resultado", other: "{count} resultados" },
      loading: "Buscando…",
      failed: "A busca não está disponível agora.",
      results: "Resultados",
    },
    readMore: "Ler mais",
    published: "Publicado",
    updated: "Atualizado",
    minRead: "min de leitura",
    by: "Por",
    featured: "Destaque",
    related: "Posts relacionados",
    tags: "Tags",
    tag: "Tag",
    category: "Categoria",
    categories: "Categorias",
    author: "Autor",
    allPosts: "Todos os posts",
    newer: "Mais novos",
    older: "Mais antigos",
    page: "Página",
    of: "de",
    pagination: "Paginação",
    share: "Compartilhar",
    copyLink: "Copiar link",
    copied: "Copiado",
    email: "E-mail",
    toc: "Nesta página",
    rss: "Feed RSS",
    translation: "Read in English",
    empty: "Nada publicado aqui ainda.",
    cta: {
      pitch: {
        title: "Solte seus agentes na Solana. Autonomia total, nos seus termos.",
        body: "Autoridade de gasto para agentes de IA na Solana. Só devnet, sem auditoria.",
        button: "Ver o pitch",
      },
      contact: {
        title: "Pronto para deixar um agente pagar?",
        body: "Vinte minutos: o que o seu agente deveria pagar, o que impede você de deixar, o que já tentou.",
        channels: { booking: "Agendar 20 minutos", whatsapp: "WhatsApp", email: "E-mail" },
        whatsappText: "Oi, li o blog do Ash e gostaria de conversar.",
        emailSubject: "Ash — pelo blog",
      },
    },
  },
} as const;
