// Tradução de pitch.en.ts, chave por chave. id, kind e dur são idênticos (o teste confere).
export const pitchPt = {
  meta: {
    pitchTitle: "Ash — o pitch",
    investorTitle: "Ash — para investidores",
    description: "Autoridade de gasto para agentes de IA na Solana, em dezoito telas e três minutos.",
  },
  deck: {
    prev: "Tela anterior",
    next: "Próxima tela",
    present: "Apresentar",
    stop: "Parar",
    notes: "Notas",
    hint: "← → para navegar · P para apresentar · N para notas",
    slide: "Tela",
  },
  slides: [
    {
      id: "hook", kind: "hook", dur: 10, kicker: "Ash",
      line: "Você entregaria o cartão da empresa para uma IA?",
      support: ["Os trilhos para o agente pagar já estão no ar. A pergunta é quem deixa."],
      notes: "Agentes já conseguem pagar APIs, computação e serviços sozinhos. Os trilhos estão no ar. A pergunta em aberto é simples: você entregaria a um deles o cartão da empresa?",
    },
    {
      id: "problem", kind: "list", dur: 12, kicker: "O problema",
      line: "Carteira na mão de agente é cheque em branco.",
      support: ["Um prompt injetado: “saque tudo”.", "Uma nova tentativa após timeout: pagou duas vezes.", "Uma chave vazada: foi tudo."],
      notes: "Dar uma carteira a um agente é dar tudo o que a chave alcança. Um prompt injetado, uma nova tentativa depois de um timeout, uma chave vazada — e o saldo inteiro está em risco.",
    },
    {
      id: "dilemma", kind: "versus", dur: 10, kicker: "O problema",
      line: "Hoje há três opções. Nenhuma cresce.",
      support: ["Entregar a chave — o pior cenário é o saldo inteiro.", "Aprovar cada pagamento na mão — a autonomia some.", "Uma carteira pequena reabastecida à mão — serve para um agente e centavos, não para quatro agentes e um fornecedor de verdade."],
      notes: "Hoje há três opções. Entregar a chave e aceitar o saldo inteiro como pior cenário. Aprovar cada pagamento na mão e perder a autonomia. Ou manter uma carteira pequena e reabastecer à mão, o que funciona para um agente e alguns centavos e para aí.",
    },
    {
      id: "answer", kind: "answer", dur: 12, kicker: "A solução",
      line: "Solte seus agentes na Solana. Autonomia total, nos seus termos.",
      support: ["Transforme prompts em pagamentos: autoridade de gasto para agentes de IA, imposta por um programa on-chain."],
      notes: "O Ash transforma prompts em pagamentos. Cada agente paga sozinho, com autonomia total dentro do orçamento e dos destinos que você define. O resto é recusado por um programa on-chain, não pelos nossos servidores.",
    },
    {
      id: "flow", kind: "flow", dur: 14, kicker: "A solução · simulação",
      line: "Um cofre, quatro agentes, um orçamento para cada.",
      support: ["Verde: passou. Vermelho: acima do limite. Âmbar tracejado: revogado — não move um centavo."],
      notes: "Aqui está funcionando. Um cofre abastece quatro agentes, cada um com o próprio orçamento. Pagamentos dentro do orçamento passam; o que passa do limite é recusado na hora; o agente com a sessão revogada não move nada.",
    },
    {
      id: "pay", kind: "pillar", dur: 10, kicker: "01 · Agentes que pagam",
      line: "Ele paga sozinho — e não sobe o próprio limite.",
      support: ["Uma chave de sessão assina cada pagamento dentro da política", "7 ferramentas do agente · nenhuma saca ou sobe limite", "Repetir o mesmo pagamento é recusado on-chain"],
      notes: "Um: agentes que pagam. Ninguém aprova cada pagamento. O agente enxerga sete ferramentas; seis leem ou pagam, a sétima só pede a um humano, e nenhuma saca ou sobe limite. Repetir o mesmo pagamento é recusado on-chain enquanto o recibo dele existir.",
    },
    {
      id: "rules", kind: "pillar", dur: 12, kicker: "02 · Regras que se sustentam",
      line: "Nenhuma política passa do teto do dono.",
      support: ["Dono — abastece, define o teto, saca sozinho", "Operador — cuida da política abaixo do teto", "Guardião — só pausa", "Agente — paga dentro da política"],
      notes: "Dois: regras que se sustentam. Um cartão corporativo para quatro pessoas. Dono, operador, guardião, agente. Nenhuma política passa do teto do dono, nenhum agente muda a própria política, e o dono sempre saca sozinho.",
    },
    {
      id: "cards", kind: "cards", dur: 10, kicker: "02 · Regras que se sustentam · simulação",
      line: "Cada agente com o seu próprio orçamento.",
      support: ["Três agentes, três desfechos: pagou, recusado, revogado."],
      notes: "Cada agente carrega o próprio orçamento. Um pagou um fornecedor. Um tentou um pagamento acima do limite e foi recusado. Um teve a sessão revogada pelo operador e não paga até receber outra.",
    },
    {
      id: "proof", kind: "pillar", dur: 10, kicker: "03 · Um registro on-chain",
      line: "Um registro que ninguém edita em silêncio.",
      support: ["Cada pagamento estende uma cadeia de hash on-chain", "13 provas Kani sobre o núcleo da política · 99,2% de cobertura de linhas no motor de política", "O programa está na devnet pública; o programa on-chain em si ainda não foi auditado"],
      notes: "Três: o registro. Cada pagamento estende uma cadeia de hash cuja ponta fica on-chain; com o histórico completo em mãos, qualquer um confirma que nada ficou de fora. Treze provas Kani cobrem o núcleo da política. O programa roda na devnet e ainda não foi auditado.",
    },
    {
      id: "compete", kind: "matrix", dur: 12, kicker: "Concorrência",
      line: "Vários impõem on-chain. Poucos juntam papéis, limites e registro.",
      support: ["Nossa leitura da documentação pública, setembro de 2026. * alegação do fornecedor, não verificada."],
      axes: { x: ["Regra imposta por um fornecedor", "Regra imposta on-chain"], y: ["Um teto", "Papéis, vários limites, registro"] },
      points: [
        { n: "Visa · Mastercard agent tokens", x: 0.1, y: 0.5 },
        { n: "Ramp agent cards + x402", x: 0.22, y: 0.64 },
        { n: "Nekuda mandates", x: 0.12, y: 0.34 },
        { n: "Privy (Stripe)", x: 0.3, y: 0.44 },
        { n: "Coinbase Agentic Wallets", x: 0.4, y: 0.28 },
        { n: "Crossmint*", x: 0.68, y: 0.42 },
        { n: "Squads spending limits", x: 0.86, y: 0.5 },
        { n: "Solana native allowances", x: 0.9, y: 0.16 },
        { n: "Ash", x: 0.9, y: 0.88, you: true },
      ],
      notes: "Redes de cartão, Ramp, Privy e Coinbase controlam o gasto do agente — nos próprios servidores. O Allowances nativo da Solana impõe um teto na rede; o Squads acrescenta destinos e janela de tempo. O Ash é na rede com papéis, vários limites ao mesmo tempo e um registro — e se apoia no Allowances nativo em vez de substituí-lo.",
    },
    {
      id: "edge", kind: "list", dur: 12, kicker: "Por que o Ash",
      line: "O que um teto sozinho não faz.",
      support: ["Limites por pagamento, por janela e no total ao mesmo tempo, com listas de destinos e tokens", "Papéis em que afrouxar só desce", "Uma chave de pausa separada do dono", "Uma cadeia de hash que permite provar que nada foi omitido", "Uma superfície de agente que não escala privilégio · Apache-2.0, sem taxa de protocolo hoje"],
      notes: "O que um teto sozinho não faz: vários limites ao mesmo tempo com listas, papéis em que o limite só aperta para baixo, uma pausa separada do dono, um histórico que permite provar omissão e um agente que não escala privilégio.",
    },
    {
      id: "now", kind: "stat", dur: 10, kicker: "Por que agora",
      line: "Os trilhos para pagar chegaram antes dos agentes.",
      support: ["x402: 52,7 milhões de dólares liquidados desde maio de 2025; cerca de 25,6 milhões parecem comércio, e 0,6% a 7,5% disso parece agente de IA (TRM Labs, set/2026)", "40 organizações entraram na x402 Foundation desde abril (Linux Foundation, jul/2026)", "Os trilhos estão sendo padronizados. O quanto um agente pode gastar não faz parte deles"],
      notes: "Por que agora: os trilhos estão no ar antes da demanda. A TRM Labs contou cinquenta e dois vírgula sete milhões de dólares em liquidações x402, e só uma fatia fina parece agente de verdade. Quarenta organizações entraram na x402 Foundation. Os trilhos estão sendo padronizados; o controle sobre quanto um agente pode gastar não faz parte deles.",
    },
    {
      id: "market", kind: "market", dur: 12, kicker: "Mercado",
      line: "Um mercado ainda em construção. Isto é o que dá para medir.",
      stats: [
        { v: "0,6–7,5%", l: "parte do comércio x402 filtrado com cara de agente de IA (TRM Labs, set/2026)" },
        { v: "93%", l: "de queda no volume diário de liquidação do x402 no ano (dados da Helios via CCN, ago/2026)" },
        { v: "40", l: "organizações na x402 Foundation desde abril (Linux Foundation, jul/2026)" },
        { v: "0", l: "clientes pagantes nossos — é cedo, e a gente sabe" },
      ],
      support: ["Vendemos a camada de controle, não um pedágio, para quem constrói na Solana agentes que precisam pagar. Ainda não sabemos quantos são."],
      notes: "O mercado, com franqueza: ainda está em construção. Pagamento de agente on-chain é uma fatia fina do x402, e o volume do x402 caiu este ano, enquanto quarenta organizações entraram na fundação dele. Vendemos a camada de controle para quem constrói na Solana agentes que precisam pagar. Estamos cedo, de propósito, e ainda não sabemos quantos são.",
    },
    {
      id: "model", kind: "list", dur: 8, kicker: "Modelo de negócio",
      line: "Protocolo Apache-2.0. Operação paga.",
      support: ["Sem taxa de protocolo hoje · Apache-2.0", "Guardião como serviço, cobrado pelo saldo que protege", "Console hospedado · custo por agente · atestação de conformidade", "Ainda não validado com compradores"],
      notes: "O protocolo tem licença Apache-2.0, sem taxa de protocolo hoje. Cobramos pela operação: guardião como serviço cobrado pelo saldo que protege, console hospedado, custo por agente e atestação. Ainda não validado com compradores.",
    },
    {
      id: "today", kind: "list", dur: 8, kicker: "Onde estamos",
      line: "Construído, testado, rodando na devnet.",
      support: ["Programa on-chain · CLI · servidor MCP · adaptador Vercel AI SDK", "Console de operação no ar em console.ash.app.br", "Mais de vinte decisões de arquitetura registradas · 0 clientes pagantes ainda"],
      notes: "Onde estamos: programa na devnet, CLI, servidor MCP, adaptador de SDK e um console de operação já no ar. Mais de vinte decisões de arquitetura registradas. Nenhum cliente pagante ainda — esse é o trabalho agora.",
    },
    {
      id: "team", kind: "list", dur: 6, kicker: "Time",
      line: "Três pessoas, no Brasil.",
      support: ["Protocolo, SDK e CLI", "Produto, console e go-to-market", "Negócios e parcerias"],
      notes: "Somos três pessoas no Brasil: uma no protocolo, SDK e CLI; uma em produto, console e go-to-market; uma em negócios e parcerias.",
    },
    {
      id: "ask", kind: "close", dur: 8, kicker: "O pedido",
      line: "Primeiro, três times na devnet. Depois, a auditoria que abre a mainnet.",
      support: ["Os primeiros times rodando agentes na devnet", "Uma auditoria profissional — o portão para a mainnet", "Console e indexer hospedados — a base de toda linha paga", "Plano: 0.x hoje · multisig 3 de 5 no 1.0-beta · renunciado no 1.0"],
      notes: "O que vem agora, em ordem: os primeiros times rodando agentes na devnet; depois uma auditoria profissional, que é o portão para a mainnet; e o console e o indexer hospedados de que toda linha paga depende. A confiança vem em fases, e isso é o plano, não o que existe hoje.",
    },
    {
      id: "thanks", kind: "thanks", dur: 4, kicker: "Ash",
      line: "Obrigado.",
      support: ["ash.app.br"],
      notes: "Obrigado. Se os seus agentes deveriam pagar por coisas, vamos conversar.",
    },
  ],
  cards: {
    left: "restam hoje", balance: "Saldo", pays: "Paga",
    items: [
      { n: "João", r: "Vendas", status: "ativo", pays: ["Clientes", "Marketing"], last: "Pagou Marketing" },
      { n: "Maria", r: "Financeiro", status: "ativo", pays: ["Fornecedores", "OpenAI"], last: "Pagamento à OpenAI recusado · acima do limite" },
      { n: "Carlos", r: "Logística", status: "revogado", pays: ["Transportadoras"], last: "Sessão revogada pelo operador" },
    ],
  },
  gate: {
    title: "Antes do pitch: com quem estamos falando?",
    sub: "Dezoito telas, três minutos. Conte quem você é e a gente abre para você.",
    name: "Nome",
    role: "Cargo",
    rolePlaceholder: "Sócio, CFO, fundador…",
    kind: "Você é",
    kinds: { investor: "Investidor", founder: "Empreendedor ou operador", other: "Outra coisa" },
    email: "E-mail",
    consent: "Concordo que o Ash guarde estes dados e me escreva sobre o Ash. Posso sair a qualquer momento.",
    consentLink: "Privacidade",
    submit: "Abrir o pitch",
    sending: "Abrindo…",
    skip: "Prefere não se identificar? O mesmo pitch está aberto para qualquer pessoa:",
    skipLink: "ver sem se identificar",
    errors: {
      name: "Conte o seu nome.",
      role: "Conte o seu cargo.",
      kind: "Escolha uma opção.",
      email: "Confira o e-mail.",
      consent: "Precisamos do seu consentimento para continuar.",
      network: "Algo deu errado do nosso lado. Tente de novo em instantes.",
    },
  },
  welcome: {
    hi: "Olá, {name}.",
    back: "Que bom te ver de novo, {name}.",
    lines: {
      investor: "Você vai ver para onde os pagamentos de agentes estão indo — e a camada que decide quanto um agente pode gastar.",
      founder: "Se os seus agentes deveriam pagar por coisas, é assim que você deixa, sem entregar a chave do cofre.",
      other: "É assim que um agente de IA gasta dinheiro sem nunca segurar a chave do cofre.",
    },
    owner: "Nesta cena, o cofre é seu. Arraste o limite e veja o que passa.",
    treasury: "cofre de {name}",
    cta: "Ver o pitch",
  },
  outro: {
    thanks: "Obrigado pela leitura, {name}.",
    lines: {
      investor: "Se isso conversa com a sua tese, a gente adoraria ouvir o que você achou — inclusive o que não te convenceu.",
      founder: "Se os seus agentes deveriam pagar por coisas, vamos testar juntos na devnet.",
      other: "Se algo aqui te serve, a gente gostaria de saber onde.",
    },
    ask: "Quer conversar com a gente?",
    yes: "Sim, quero conversar",
    no: "Agora não",
    pick: "Escolha o que for melhor para você:",
    channels: { booking: "Agendar 20 minutos", whatsapp: "WhatsApp", email: "E-mail" },
    none: "Obrigado. Fale com a gente pelo site quando quiser.",
    later: "Tudo bem. O pitch fica aqui para quando você quiser.",
    whatsappText: "Oi, acabei de ver o pitch do Ash e gostaria de conversar.",
    emailSubject: "Ash — depois do pitch",
    replay: "Rever o pitch",
    site: "Conhecer o site do Ash",
  },
} as const;
