import type { DashboardState } from "@/lib/schema";

const NOW = "2026-09-20T00:00:00.000Z";

/**
 * First-run content so the dashboard has something to show before anything is
 * bootstrapped on-chain. Every row is flagged `demo: true`: the UI labels them
 * and Settings → Data can clear them. Demo rows carry no wallet address on
 * purpose — a placeholder string would otherwise reach the RPC as a real query.
 */
export function seedState(): DashboardState {
  return {
    version: 1,
    workflows: [
      {
        id: "w_demo_loja",
        name: "My Online Store",
        description: "E-commerce with sales and support agents",
        icon: "🏪",
        treasuryAddress: null,
        ownerAddress: null,
        cluster: "devnet",
        demo: true,
        demoBalanceUsd: 2450,
        createdAt: NOW,
      },
      {
        id: "w_demo_defi",
        name: "DeFi Trading",
        description: "Trading and market analysis agents",
        icon: "📈",
        treasuryAddress: null,
        ownerAddress: null,
        cluster: "devnet",
        demo: true,
        demoBalanceUsd: 550,
        createdAt: NOW,
      },
      {
        id: "w_demo_fornec",
        name: "Vendor Payments",
        description: "Accounts payable automation",
        icon: "🏭",
        treasuryAddress: null,
        ownerAddress: null,
        cluster: "devnet",
        demo: true,
        demoBalanceUsd: 2800,
        createdAt: NOW,
      },
    ],
    agents: [
      agent("a_demo_maria", "Maria", "Finance Manager", "w_demo_loja", 50, 200, 12, [
        "OpenAI",
        "Vendors",
      ]),
      agent("a_demo_joao", "João", "Sales Assistant", "w_demo_loja", 100, 150, 45, [
        "Customers",
        "Marketing",
      ]),
      agent("a_demo_ana", "Ana", "Support", "w_demo_loja", 0, 0, 0, []),
      {
        ...agent("a_demo_carlos", "Carlos", "Logistics", "w_demo_loja", 30, 75, 8, ["Carriers"]),
        status: "paused",
      },
      agent("a_demo_trader", "Trader Bot", "DeFi Trader", "w_demo_defi", 100, 500, 67, [
        "Jupiter",
        "Raydium",
      ]),
      agent("a_demo_research", "Researcher", "Market Analyst", "w_demo_defi", 20, 50, 5, [
        "Data APIs",
      ]),
      agent("a_demo_cfo", "CFO Bot", "Payments", "w_demo_fornec", 500, 2000, 320, [
        "Vendor A",
        "Vendor B",
      ]),
      agent("a_demo_ap", "AP Assistant", "Accounts Payable", "w_demo_fornec", 200, 800, 89, [
        "Vendors",
      ]),
    ],
    mcps: [
      {
        id: "m_agent_rails",
        name: "Agent Rails Payments",
        description: "Payments with limits and on-chain audit",
        enabled: true,
        scope: "global",
        scopeName: null,
        // The real server from packages/mcp. The env keys are seeded empty on
        // purpose: they name what the user has to fill in, and an empty value
        // is dropped from the export rather than shipped as a set-but-blank
        // variable the server would then reject for the wrong reason.
        command: "agent-rails-mcp",
        args: [],
        env: {
          AGENT_RAILS_RPC: "",
          AGENT_RAILS_SESSION: "",
          AGENT_RAILS_SIGNER: "",
        },
        demo: false,
      },
      {
        id: "m_jupiter",
        name: "Jupiter Swap",
        description: "Swap tokens within the agent's limit",
        enabled: false,
        scope: "workflow",
        scopeName: "DeFi Trading",
        command: "",
        args: [],
        env: {},
        demo: true,
      },
      {
        id: "m_superteam",
        name: "Superteam Earn",
        description: "Find bounties and grants for agents",
        enabled: false,
        scope: "global",
        scopeName: null,
        command: "",
        args: [],
        env: {},
        demo: true,
      },
      {
        id: "m_helius",
        name: "Helius RPC",
        description: "On-chain data and webhooks",
        enabled: false,
        scope: "global",
        scopeName: null,
        command: "",
        args: [],
        env: {},
        demo: true,
      },
    ],
    // RAG and Integrations have no backend: their pages were pruned, so seeding
    // rows here would write state nothing renders. The collections stay in the
    // schema so an existing dashboard.json still parses.
    rag: [],
    skills: [
      {
        id: "s_pagar",
        name: "Make payment",
        description: "Execute payment within limits",
        icon: "\u{1F4B0}",
        scope: "global",
        scopeName: null,
        enabled: true,
        demo: false,
        content: [
          "## When to use",
          "",
          "The user asked you to pay someone, settle an invoice, or send funds.",
          "",
          "## How",
          "",
          "1. Resolve the destination to a base58 address. Never guess one.",
          "2. Call `create_payment_intent` with the amount, mint and destination.",
          "3. Read the preflight result back to the user **before** executing:",
          "   it reports the per-tx, windowed and lifetime headroom the policy",
          "   leaves, and refusing early is cheaper than a failed transaction.",
          "4. Execute only after the user confirms the quoted amount.",
          "",
          "## Rules",
          "",
          "- One `intent_id` per payment. Retrying reuses the same id, so a",
          "  duplicate never becomes a second transfer.",
          "- A refusal is an answer. Report the reason code verbatim and stop;",
          "  do not try a smaller amount to feel your way around a limit.",
          "- You cannot raise a limit, unpause, or withdraw. If the user asks,",
          "  tell them it is an owner action in the dashboard.",
        ].join("\n"),
      },
      {
        id: "s_saldo",
        name: "Check balance",
        description: "Check vault or agent balance",
        icon: "\u{1F4CA}",
        scope: "global",
        scopeName: null,
        enabled: true,
        demo: false,
        content: [
          "## When to use",
          "",
          'Any question about "how much is left", remaining limit, or whether a',
          "payment would fit.",
          "",
          "## How",
          "",
          "1. Read the vault balance and the session's remaining headroom.",
          "2. Answer with both: the vault can hold plenty while the window is",
          "   already spent, and only the smaller of the two is spendable now.",
          "3. State the window that applies and when it rolls over. Windows are",
          "   fixed epoch buckets, not a rolling 24h.",
          "",
          "## Rules",
          "",
          "- Give figures in the mint's own units, with the ticker.",
          "- If a read fails, say so. Never fill a gap with an estimate.",
        ].join("\n"),
      },
      {
        id: "s_pool",
        name: "Analyze liquidity pool",
        description: "Evaluate DeFi pools before operating",
        icon: "\u{1F4C8}",
        scope: "workflow",
        scopeName: "DeFi Trading",
        enabled: false,
        demo: true,
        content: [
          "## When to use",
          "",
          "Before entering any pool position.",
          "",
          "## Checklist",
          "",
          "- TVL and 24h volume; a pool with volume far above TVL is thin.",
          "- Fee tier against realised volatility of the pair.",
          "- Token mint authority and freeze authority: both should be renounced.",
          "- Impermanent-loss exposure at \u00b120% price movement.",
          "",
          "Report the checklist result before proposing a position, and say",
          "plainly when the data is missing rather than scoring it anyway.",
        ].join("\n"),
      },
      {
        id: "s_stop",
        name: "Automatic stop-loss",
        description: "Sell automatically on loss",
        icon: "\u26A1",
        scope: "agent",
        scopeName: "Trader Bot",
        enabled: false,
        demo: true,
        content: [
          "## When to use",
          "",
          "A held position moves against the entry price by more than the",
          "configured threshold.",
          "",
          "## How",
          "",
          "1. Compare the mark price to the recorded entry.",
          "2. Below the threshold, exit the whole position in one order.",
          "3. Record the exit and the realised result.",
          "",
          "## Rules",
          "",
          "- Never average down to avoid triggering the stop.",
          "- The exit is still a payment: it passes the same policy checks, and",
          "  a refusal means the position stays open. Escalate, do not retry.",
        ].join("\n"),
      },
    ],
    apiKeys: [],
    integrations: [],
    profile: { displayName: "", company: "", bio: "", email: "" },
    settings: { language: "en", emailNotifications: false, limitAlerts: true, alertWebhookUrl: "" },
  };
}

function agent(
  id: string,
  name: string,
  role: string,
  workflowId: string,
  dailyLimitUsd: number,
  demoBalanceUsd: number,
  demoSpentUsd: number,
  paysTo: string[],
): DashboardState["agents"][number] {
  return {
    id,
    name,
    role,
    workflowId,
    walletAddress: null,
    sessionAddress: null,
    dailyLimitUsd,
    paysTo,
    receivesFrom: "Workflow vault",
    status: "active",
    demo: true,
    demoBalanceUsd,
    demoSpentUsd,
    createdAt: NOW,
  };
}
