import type {
  Agent,
  ApiKeyEntry,
  McpServer,
  RagDocument,
  Skill,
  WalletInfo,
  Workflow,
} from "./types";

const agentsWorkflow1: Agent[] = [
  {
    id: "a1",
    name: "Maria",
    role: "Gerente Financeira",
    workflowId: "w1",
    walletAddress: "7xK9mN2pQr4sT8vW1yZ3aB5cD6eF7gH8",
    balanceUsd: 200,
    dailyLimitUsd: 50,
    dailySpentUsd: 12,
    paysTo: ["OpenAI", "Fornecedores"],
    receivesFrom: "Cofre Minha Loja",
    status: "active",
  },
  {
    id: "a2",
    name: "João",
    role: "Assistente de Vendas",
    workflowId: "w1",
    walletAddress: "9yL0nO3qRs5tU9wX2zA4bC6dE7fG8hI9",
    balanceUsd: 150,
    dailyLimitUsd: 100,
    dailySpentUsd: 45,
    paysTo: ["Clientes", "Marketing"],
    receivesFrom: "Cofre Minha Loja",
    status: "active",
  },
  {
    id: "a3",
    name: "Ana",
    role: "Suporte",
    workflowId: "w1",
    walletAddress: "3zM1pP4rSt6uV0xY3aB5cD7eF8gH9iJ0",
    balanceUsd: 0,
    dailyLimitUsd: 0,
    dailySpentUsd: 0,
    paysTo: [],
    receivesFrom: "Cofre Minha Loja",
    status: "active",
  },
  {
    id: "a4",
    name: "Carlos",
    role: "Logística",
    workflowId: "w1",
    walletAddress: "5bN2qQ5sTu7vW1yZ4bC6dE8fG9hI0jK1",
    balanceUsd: 75,
    dailyLimitUsd: 30,
    dailySpentUsd: 8,
    paysTo: ["Transportadoras"],
    receivesFrom: "Cofre Minha Loja",
    status: "paused",
  },
];

const agentsWorkflow2: Agent[] = [
  {
    id: "a5",
    name: "Trader Bot",
    role: "Trader DeFi",
    workflowId: "w2",
    walletAddress: "8cO3rR6tUv8wX2zA5cD7eF9gH0iJ1kL2",
    balanceUsd: 500,
    dailyLimitUsd: 100,
    dailySpentUsd: 67,
    paysTo: ["Jupiter", "Raydium"],
    receivesFrom: "Cofre DeFi Trading",
    status: "active",
  },
  {
    id: "a6",
    name: "Researcher",
    role: "Analista de Mercado",
    workflowId: "w2",
    walletAddress: "1dP4sS7uVw9yZ3bD6eF8gH1iJ2kL3mN4",
    balanceUsd: 50,
    dailyLimitUsd: 20,
    dailySpentUsd: 5,
    paysTo: ["APIs de dados"],
    receivesFrom: "Cofre DeFi Trading",
    status: "active",
  },
];

const agentsWorkflow3: Agent[] = [
  {
    id: "a7",
    name: "CFO Bot",
    role: "Pagamentos",
    workflowId: "w3",
    walletAddress: "6eQ5tT8vWx0zA4cE7fG9hI2jK3lM4nO5",
    balanceUsd: 2000,
    dailyLimitUsd: 500,
    dailySpentUsd: 320,
    paysTo: ["Fornecedor A", "Fornecedor B"],
    receivesFrom: "Cofre Fornecedores",
    status: "active",
  },
  {
    id: "a8",
    name: "AP Assistant",
    role: "Contas a Pagar",
    workflowId: "w3",
    walletAddress: "2fR6uU9wXy1aB5dF8gH0iJ3kL4mN5oP6",
    balanceUsd: 800,
    dailyLimitUsd: 200,
    dailySpentUsd: 89,
    paysTo: ["Fornecedores"],
    receivesFrom: "Cofre Fornecedores",
    status: "active",
  },
];

export const mockWorkflows: Workflow[] = [
  {
    id: "w1",
    name: "Minha Loja Online",
    description: "E-commerce com agentes de vendas e suporte",
    icon: "🏪",
    treasuryBalanceUsd: 2450,
    agents: agentsWorkflow1,
  },
  {
    id: "w2",
    name: "DeFi Trading",
    description: "Agentes de trading e análise de mercado",
    icon: "📈",
    treasuryBalanceUsd: 550,
    agents: agentsWorkflow2,
  },
  {
    id: "w3",
    name: "Pagamentos Fornecedores",
    description: "Automação de contas a pagar",
    icon: "🏭",
    treasuryBalanceUsd: 2800,
    agents: agentsWorkflow3,
  },
];

export const mockWallets: WalletInfo[] = [
  {
    id: "tw1",
    name: "Cofre Principal",
    address: "9xYzAbC1234567890defGhIjKlMnOpQrStUvWx",
    type: "treasury",
    balanceUsd: 2450,
    workflowId: "w1",
    workflowName: "Minha Loja Online",
  },
  {
    id: "aw1",
    name: "Maria — Gerente",
    address: "7xK9mN2pQr4sT8vW1yZ3aB5cD6eF7gH8",
    type: "agent",
    balanceUsd: 200,
    workflowId: "w1",
    workflowName: "Minha Loja Online",
    agentId: "a1",
    agentName: "Maria",
    dailyLimitUsd: 50,
    dailySpentUsd: 12,
  },
  {
    id: "aw2",
    name: "João — Vendas",
    address: "9yL0nO3qRs5tU9wX2zA4bC6dE7fG8hI9",
    type: "agent",
    balanceUsd: 150,
    workflowId: "w1",
    workflowName: "Minha Loja Online",
    agentId: "a2",
    agentName: "João",
    dailyLimitUsd: 100,
    dailySpentUsd: 45,
  },
  {
    id: "tw2",
    name: "Cofre DeFi",
    address: "4hIjKlMnOpQrStUvWxYzAbC1234567890de",
    type: "treasury",
    balanceUsd: 550,
    workflowId: "w2",
    workflowName: "DeFi Trading",
  },
  {
    id: "ow1",
    name: "Sua Wallet",
    address: "OwnerWallet1234567890abcdefghijklmnop",
    type: "owner",
    balanceUsd: 12500,
    workflowId: "w1",
    workflowName: "Todas",
  },
];

export const mockMcps: McpServer[] = [
  {
    id: "m1",
    name: "Agent Rails Payments",
    description: "Pagamentos com limites e auditoria on-chain",
    enabled: true,
    scope: "global",
  },
  {
    id: "m2",
    name: "Jupiter Swap",
    description: "Trocar tokens (max $100/dia)",
    enabled: true,
    scope: "workflow",
    scopeName: "DeFi Trading",
  },
  {
    id: "m3",
    name: "Superteam Earn",
    description: "Buscar bounties e grants para agentes",
    enabled: false,
    scope: "global",
  },
  {
    id: "m4",
    name: "Helius RPC",
    description: "Dados on-chain e webhooks",
    enabled: true,
    scope: "global",
  },
];

export const mockRagDocs: RagDocument[] = [
  {
    id: "r1",
    name: "Catálogo de produtos.pdf",
    type: "pdf",
    status: "indexed",
    scope: "workflow",
    scopeName: "Minha Loja Online",
  },
  {
    id: "r2",
    name: "Política de devolução.md",
    type: "md",
    status: "indexed",
    scope: "workflow",
    scopeName: "Minha Loja Online",
  },
  {
    id: "r3",
    name: "FAQ atendimento.txt",
    type: "md",
    status: "indexed",
    scope: "agent",
    scopeName: "Ana — Suporte",
  },
  {
    id: "r4",
    name: "Manual DeFi protocols",
    type: "url",
    status: "indexing",
    scope: "workflow",
    scopeName: "DeFi Trading",
  },
];

export const mockSkills: Skill[] = [
  {
    id: "s1",
    name: "Fazer pagamento",
    description: "Executar pagamento dentro dos limites",
    icon: "💰",
    scope: "global",
    enabled: true,
  },
  {
    id: "s2",
    name: "Consultar saldo",
    description: "Verificar saldo do cofre ou agente",
    icon: "📊",
    scope: "global",
    enabled: true,
  },
  {
    id: "s3",
    name: "Analisar pool de liquidez",
    description: "Avaliar pools DeFi antes de operar",
    icon: "📈",
    scope: "workflow",
    scopeName: "DeFi Trading",
    enabled: true,
  },
  {
    id: "s4",
    name: "Stop-loss automático",
    description: "Vender automaticamente em perda",
    icon: "⚡",
    scope: "agent",
    scopeName: "Trader Bot",
    enabled: true,
  },
];

export const mockApiKeys: ApiKeyEntry[] = [
  {
    id: "k1",
    provider: "Anthropic",
    keyMasked: "sk-ant-••••••••••••••••",
    status: "disconnected",
  },
  {
    id: "k2",
    provider: "OpenAI",
    keyMasked: "sk-••••••••••••••••••••",
    status: "disconnected",
  },
];

export const allAgents: Agent[] = mockWorkflows.flatMap((w) => w.agents);
