import type { LegalDoc } from "./types";

/**
 * Terms of Service, both languages. The third-party provisions in §4 and §5 exist because the
 * model route is OpenRouter → Anthropic: OpenRouter's terms (§5.2) make the operator require
 * its customers to follow OpenRouter's terms and the model provider's, and bar reselling API
 * access. See docs/runbooks/openrouter-chat-integration.md and chat-credit-billing.md.
 */
export const TERMS: Record<"en" | "pt-BR", LegalDoc> = {
  en: {
    title: "Terms of Service",
    updated: "2 October 2026",
    intro:
      "These terms govern your use of Agent Rails (the “Service”), operated by {entity} (“we”, “us”). By creating an account or using the Service you agree to them. If you do not agree, do not use the Service.",
    sections: [
      {
        id: "service",
        heading: "The Service",
        paragraphs: [
          "Agent Rails is a dashboard for managing treasuries, spending policies and sessions for autonomous software agents that pay on the Solana blockchain, with a read-only assistant that answers questions about your workspace.",
          "The on-chain program is separate from this dashboard. We do not hold your on-chain funds: vaults are controlled by the keys and wallets you connect, and a blockchain transaction cannot be reversed by us or by anyone else.",
        ],
      },
      {
        id: "accounts",
        heading: "Accounts",
        paragraphs: [
          "You must be at least 18 and able to enter a binding contract. You are responsible for your sign-in method (email, Google account or wallet), for every wallet and key you connect or generate, and for everything done through your account.",
          "Keep your keys and recovery material to yourself. We cannot recover a private key we never held.",
        ],
      },
      {
        id: "assistant",
        heading: "The assistant",
        paragraphs: [
          "The assistant is read-only: it can describe what your workspace shows, and it has no ability to create sessions, change limits, move funds or sign anything. Anything that changes a limit or moves money is done by you, in the dashboard or the command line, with your own wallet.",
          "Assistant output is generated by an AI model and can be wrong, incomplete or out of date. It is not financial, legal or tax advice. Check anything that matters against the on-chain data and your policies before you act on it.",
        ],
      },
      {
        id: "providers",
        heading: "Third-party model providers",
        paragraphs: [
          "To answer you, the assistant sends your messages and the workspace context needed to answer them (for example names of workflows and agents, balances and policy summaries) to OpenRouter, which routes the request to a model provider, currently Anthropic. Those companies process your inputs and the model’s outputs. The Privacy Policy describes what is sent.",
          "You agree to use the assistant only in accordance with these terms and with the terms that apply to the underlying services, and you agree that:",
        ],
        items: [
          "you will comply with Anthropic’s Commercial Terms of Service and Usage Policy (Acceptable Use Policy), and with OpenRouter’s Terms of Service, each as published and updated from time to time;",
          "you are responsible for the content you submit and for your use of the outputs;",
          "we may refuse, limit or stop a request, or suspend access, if we reasonably believe it breaks those terms or puts our access to those providers at risk.",
        ],
      },
      {
        id: "use",
        heading: "Acceptable use",
        paragraphs: ["You may not, and may not help anyone else to:"],
        items: [
          "use the Service, its outputs or its responses to develop, train or improve a competing AI model or a competing service;",
          "resell, sublicense, share or give third parties access to the Service or to the underlying models, or build a proxy or wrapper that exposes either as an API;",
          "scrape, crawl, bulk-extract or systematically copy the Service, its content or its outputs;",
          "probe, test or attempt to circumvent the security, rate limits, billing or usage restrictions of the Service or of the providers behind it, including red-teaming, or attempts to extract system prompts, keys or other users’ data, without our written permission;",
          "submit unlawful content, content that infringes others’ rights, or data you are not entitled to share, or use the Service in a way that breaks the law or the Anthropic Usage Policy;",
          "submit secrets you do not want a third party to process, such as private keys, seed phrases or passwords. The assistant never needs them.",
        ],
      },
      {
        id: "credit",
        heading: "Credit, pricing and payments",
        paragraphs: [
          "The assistant is paid for with prepaid credit. Each reply debits the cost the model provider charged us for it plus a service fee, currently 20% of that cost, rounded up. Every debit is itemised on your account page with the model, token counts, the provider cost and the fee. We may change the fee or the models offered, and a change applies to replies made after it is published.",
          "Deposits are made in USDC on Solana. A confirmed deposit is final and is credited at one dollar per USDC. Network fees are charged by the network. Credit is a prepaid balance for using the Service; it is not a bank deposit, earns no interest and is not legal tender.",
          "You can ask to withdraw an unused balance with Withdraw. Requests are reviewed and paid by us, in USDC to the address you give, and we may decline one, for example to prevent fraud or to comply with law, in which case the amount returns to your balance. A reply that has already been generated is charged even if you stop it midway, because the provider charges us for it.",
          "Taxes, if any, are your responsibility unless the law says otherwise.",
        ],
      },
      {
        id: "content",
        heading: "Your content",
        paragraphs: [
          "You keep your rights in what you submit and in your workspace data. You give us the limited permission needed to run the Service for you: to store your workspace data, to send your assistant messages to the providers in section 4, and to show you the results.",
        ],
      },
      {
        id: "availability",
        heading: "Availability and changes",
        paragraphs: [
          "The Service, and the providers behind it, may be unavailable, slow or changed at any time. We may add, change or remove features. The software is under active development and is provided as it is.",
        ],
      },
      {
        id: "liability",
        heading: "Disclaimers and liability",
        paragraphs: [
          "To the fullest extent the law allows, the Service is provided “as is” and “as available”, without warranties of any kind, express or implied, including fitness for a particular purpose, accuracy of assistant output, and uninterrupted or error-free operation. We do not warrant that spending policies will prevent every loss: smart contracts, wallets and networks can fail.",
          "To the fullest extent the law allows, we are not liable for indirect, incidental, special or consequential damages, or for lost profits, funds or data, and our total liability for any claim is limited to the amount you paid us for the Service in the three months before the claim arose. Nothing in these terms limits liability that cannot be limited by law.",
        ],
      },
      {
        id: "termination",
        heading: "Suspension and termination",
        paragraphs: [
          "You may stop using the Service at any time and may withdraw your unused balance as described above. We may suspend or end your access if you break these terms, if we must for legal or security reasons, or if a provider requires it. Sections that by their nature should survive, including acceptable use, liability and governing law, survive termination.",
        ],
      },
      {
        id: "law",
        heading: "Governing law",
        paragraphs: [
          "These terms are governed by {law}. Disputes are for the courts named there, except where mandatory consumer law gives you the right to go to the courts where you live.",
        ],
      },
      {
        id: "changes",
        heading: "Changes to these terms and contact",
        paragraphs: [
          "We may update these terms. The date at the top changes when we do, and material changes will be announced in the Service. Using the Service after a change means you accept it.",
          "Questions about these terms: {email}.",
        ],
      },
    ],
  },
  "pt-BR": {
    title: "Termos de Serviço",
    updated: "2 de outubro de 2026",
    intro:
      "Estes termos regem o uso do Agent Rails (o “Serviço”), operado por {entity} (“nós”). Ao criar uma conta ou usar o Serviço, você concorda com eles. Se não concordar, não use o Serviço.",
    sections: [
      {
        id: "service",
        heading: "O Serviço",
        paragraphs: [
          "O Agent Rails é um painel para gerenciar tesourarias, políticas de gasto e sessões de agentes de software autônomos que pagam na blockchain Solana, com um assistente somente leitura que responde perguntas sobre o seu espaço de trabalho.",
          "O programa on-chain é separado deste painel. Não custodiamos seus fundos on-chain: os cofres são controlados pelas chaves e carteiras que você conecta, e uma transação em blockchain não pode ser revertida por nós nem por ninguém.",
        ],
      },
      {
        id: "accounts",
        heading: "Contas",
        paragraphs: [
          "Você deve ter ao menos 18 anos e capacidade para contratar. Você é responsável pelo seu método de acesso (e-mail, conta Google ou carteira), por cada carteira e chave que conectar ou gerar e por tudo o que for feito pela sua conta.",
          "Mantenha suas chaves e dados de recuperação só com você. Não podemos recuperar uma chave privada que nunca tivemos.",
        ],
      },
      {
        id: "assistant",
        heading: "O assistente",
        paragraphs: [
          "O assistente é somente leitura: descreve o que o seu espaço de trabalho mostra e não pode criar sessões, alterar limites, mover fundos nem assinar nada. Tudo o que altera um limite ou move dinheiro é feito por você, no painel ou na linha de comando, com a sua própria carteira.",
          "A resposta do assistente é gerada por um modelo de IA e pode estar errada, incompleta ou desatualizada. Não é aconselhamento financeiro, jurídico ou tributário. Confira o que importa nos dados on-chain e nas suas políticas antes de agir.",
        ],
      },
      {
        id: "providers",
        heading: "Provedores de modelos de terceiros",
        paragraphs: [
          "Para responder, o assistente envia suas mensagens e o contexto do espaço de trabalho necessário (por exemplo nomes de fluxos e agentes, saldos e resumos de políticas) à OpenRouter, que encaminha o pedido a um provedor de modelo, hoje a Anthropic. Essas empresas processam o que você envia e as respostas do modelo. A Política de Privacidade descreve o que é enviado.",
          "Você concorda em usar o assistente somente conforme estes termos e os termos dos serviços subjacentes, e concorda que:",
        ],
        items: [
          "cumprirá os Termos Comerciais de Serviço e a Política de Uso (Acceptable Use Policy) da Anthropic e os Termos de Serviço da OpenRouter, conforme publicados e atualizados;",
          "é responsável pelo conteúdo que envia e pelo uso que faz das respostas;",
          "podemos recusar, limitar ou interromper um pedido, ou suspender o acesso, se entendermos razoavelmente que ele viola esses termos ou põe em risco o nosso acesso a esses provedores.",
        ],
      },
      {
        id: "use",
        heading: "Uso aceitável",
        paragraphs: ["Você não pode, nem ajudar outra pessoa a:"],
        items: [
          "usar o Serviço, suas saídas ou respostas para desenvolver, treinar ou melhorar um modelo de IA concorrente ou um serviço concorrente;",
          "revender, sublicenciar, compartilhar ou dar a terceiros acesso ao Serviço ou aos modelos subjacentes, nem construir um proxy ou wrapper que exponha um deles como API;",
          "fazer scraping, rastrear, extrair em massa ou copiar sistematicamente o Serviço, seu conteúdo ou suas saídas;",
          "sondar, testar ou tentar contornar a segurança, os limites de uso, a cobrança ou as restrições do Serviço ou dos provedores por trás dele, inclusive red-teaming ou tentativas de extrair prompts de sistema, chaves ou dados de outros usuários, sem nossa autorização por escrito;",
          "enviar conteúdo ilícito, que viole direitos de terceiros, ou dados que você não pode compartilhar, nem usar o Serviço de forma contrária à lei ou à Política de Uso da Anthropic;",
          "enviar segredos que você não quer que um terceiro processe, como chaves privadas, frases-semente ou senhas. O assistente nunca precisa deles.",
        ],
      },
      {
        id: "credit",
        heading: "Crédito, preços e pagamentos",
        paragraphs: [
          "O assistente é pago com crédito pré-pago. Cada resposta debita o custo que o provedor do modelo nos cobrou por ela mais uma taxa de serviço, hoje de 20% desse custo, arredondada para cima. Cada débito é detalhado na página da sua conta, com o modelo, a contagem de tokens, o custo do provedor e a taxa. Podemos alterar a taxa ou os modelos oferecidos, e a mudança vale para respostas feitas depois de publicada.",
          "Os depósitos são feitos em USDC na Solana. Um depósito confirmado é definitivo e é creditado a um dólar por USDC. As taxas de rede são cobradas pela rede. O crédito é um saldo pré-pago para usar o Serviço; não é depósito bancário, não rende juros e não é moeda de curso legal.",
          "Você pode pedir a retirada do saldo não usado em Retirar. Os pedidos são analisados e pagos por nós, em USDC no endereço informado, e podemos recusar um pedido, por exemplo para prevenir fraude ou cumprir a lei; nesse caso o valor volta ao seu saldo. Uma resposta já gerada é cobrada mesmo se você a interromper no meio, porque o provedor nos cobra por ela.",
          "Tributos, se houver, são de sua responsabilidade, salvo disposição legal em contrário.",
        ],
      },
      {
        id: "content",
        heading: "Seu conteúdo",
        paragraphs: [
          "Você mantém seus direitos sobre o que envia e sobre os dados do seu espaço de trabalho. Você nos dá a permissão limitada necessária para operar o Serviço para você: armazenar os dados do seu espaço de trabalho, enviar suas mensagens ao assistente aos provedores da seção 4 e mostrar os resultados.",
        ],
      },
      {
        id: "availability",
        heading: "Disponibilidade e mudanças",
        paragraphs: [
          "O Serviço, e os provedores por trás dele, podem ficar indisponíveis, lentos ou mudar a qualquer momento. Podemos adicionar, alterar ou remover recursos. O software está em desenvolvimento ativo e é fornecido no estado em que se encontra.",
        ],
      },
      {
        id: "liability",
        heading: "Isenções e responsabilidade",
        paragraphs: [
          "Na máxima extensão permitida em lei, o Serviço é fornecido “como está” e “conforme disponível”, sem garantias de qualquer tipo, expressas ou implícitas, inclusive de adequação a um fim específico, de exatidão das respostas do assistente e de funcionamento ininterrupto ou sem erros. Não garantimos que as políticas de gasto evitem toda perda: contratos inteligentes, carteiras e redes podem falhar.",
          "Na máxima extensão permitida em lei, não respondemos por danos indiretos, incidentais, especiais ou consequentes, nem por lucros cessantes, perda de fundos ou de dados, e nossa responsabilidade total por qualquer reclamação se limita ao valor que você nos pagou pelo Serviço nos três meses anteriores ao fato. Nada nestes termos limita responsabilidade que a lei não permita limitar.",
        ],
      },
      {
        id: "termination",
        heading: "Suspensão e encerramento",
        paragraphs: [
          "Você pode deixar de usar o Serviço a qualquer momento e retirar o saldo não usado conforme descrito acima. Podemos suspender ou encerrar seu acesso se você violar estes termos, se precisarmos por razões legais ou de segurança, ou se um provedor exigir. As cláusulas que por natureza devam subsistir, como uso aceitável, responsabilidade e lei aplicável, subsistem ao encerramento.",
        ],
      },
      {
        id: "law",
        heading: "Lei aplicável",
        paragraphs: [
          "Estes termos são regidos por {law}. Os litígios cabem aos tribunais ali indicados, salvo quando a lei de defesa do consumidor garantir a você o direito de ir ao foro do seu domicílio.",
        ],
      },
      {
        id: "changes",
        heading: "Alterações destes termos e contato",
        paragraphs: [
          "Podemos atualizar estes termos. A data no topo muda quando isso acontecer, e mudanças relevantes serão avisadas no Serviço. Continuar a usar o Serviço após uma mudança significa aceitá-la.",
          "Dúvidas sobre estes termos: {email}.",
        ],
      },
    ],
  },
};
